package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 11 19:38:04 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprisalHisLine_VORowImpl extends ViewRowImpl {
    public static final int ENTITY_APPRISALHISLINE_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AchievementDate,
        ActualValue,
        AppraisalHistHdrId,
        AppraisalHistLineId,
        Comments,
        CompletePercent,
        CreatedBy,
        Detail,
        MeasureComments,
        MeasureName,
        MeasureType,
        MeasureUom,
        MeasurementStyle,
        NextReviewDate,
        ObjectiveComments,
        ObjectiveName,
        ObjectiveStartDate,
        ObjectiveTargetDate,
        SuccessCriteria,
        TargetValue,
        WeightingPercent;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ACHIEVEMENTDATE = AttributesEnum.AchievementDate.index();
    public static final int ACTUALVALUE = AttributesEnum.ActualValue.index();
    public static final int APPRAISALHISTHDRID = AttributesEnum.AppraisalHistHdrId.index();
    public static final int APPRAISALHISTLINEID = AttributesEnum.AppraisalHistLineId.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int COMPLETEPERCENT = AttributesEnum.CompletePercent.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int DETAIL = AttributesEnum.Detail.index();
    public static final int MEASURECOMMENTS = AttributesEnum.MeasureComments.index();
    public static final int MEASURENAME = AttributesEnum.MeasureName.index();
    public static final int MEASURETYPE = AttributesEnum.MeasureType.index();
    public static final int MEASUREUOM = AttributesEnum.MeasureUom.index();
    public static final int MEASUREMENTSTYLE = AttributesEnum.MeasurementStyle.index();
    public static final int NEXTREVIEWDATE = AttributesEnum.NextReviewDate.index();
    public static final int OBJECTIVECOMMENTS = AttributesEnum.ObjectiveComments.index();
    public static final int OBJECTIVENAME = AttributesEnum.ObjectiveName.index();
    public static final int OBJECTIVESTARTDATE = AttributesEnum.ObjectiveStartDate.index();
    public static final int OBJECTIVETARGETDATE = AttributesEnum.ObjectiveTargetDate.index();
    public static final int SUCCESSCRITERIA = AttributesEnum.SuccessCriteria.index();
    public static final int TARGETVALUE = AttributesEnum.TargetValue.index();
    public static final int WEIGHTINGPERCENT = AttributesEnum.WeightingPercent.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ApprisalHisLine_VORowImpl() {
    }

    /**
     * Gets ApprisalHisLine_EO entity object.
     * @return the ApprisalHisLine_EO
     */
    public EntityImpl getApprisalHisLine_EO() {
        return (EntityImpl) getEntity(ENTITY_APPRISALHISLINE_EO);
    }

    /**
     * Gets the attribute value for ACHIEVEMENT_DATE using the alias name AchievementDate.
     * @return the ACHIEVEMENT_DATE
     */
    public Timestamp getAchievementDate() {
        return (Timestamp) getAttributeInternal(ACHIEVEMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACHIEVEMENT_DATE using the alias name AchievementDate.
     * @param value value to set the ACHIEVEMENT_DATE
     */
    public void setAchievementDate(Timestamp value) {
        setAttributeInternal(ACHIEVEMENTDATE, value);
    }

    /**
     * Gets the attribute value for ACTUAL_VALUE using the alias name ActualValue.
     * @return the ACTUAL_VALUE
     */
    public BigDecimal getActualValue() {
        return (BigDecimal) getAttributeInternal(ACTUALVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTUAL_VALUE using the alias name ActualValue.
     * @param value value to set the ACTUAL_VALUE
     */
    public void setActualValue(BigDecimal value) {
        setAttributeInternal(ACTUALVALUE, value);
    }

    /**
     * Gets the attribute value for APPRAISAL_HIST_HDR_ID using the alias name AppraisalHistHdrId.
     * @return the APPRAISAL_HIST_HDR_ID
     */
    public BigDecimal getAppraisalHistHdrId() {
        return (BigDecimal) getAttributeInternal(APPRAISALHISTHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_HIST_HDR_ID using the alias name AppraisalHistHdrId.
     * @param value value to set the APPRAISAL_HIST_HDR_ID
     */
    public void setAppraisalHistHdrId(BigDecimal value) {
        setAttributeInternal(APPRAISALHISTHDRID, value);
    }

    /**
     * Gets the attribute value for APPRAISAL_HIST_LINE_ID using the alias name AppraisalHistLineId.
     * @return the APPRAISAL_HIST_LINE_ID
     */
    public BigDecimal getAppraisalHistLineId() {
        return (BigDecimal) getAttributeInternal(APPRAISALHISTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_HIST_LINE_ID using the alias name AppraisalHistLineId.
     * @param value value to set the APPRAISAL_HIST_LINE_ID
     */
    public void setAppraisalHistLineId(BigDecimal value) {
        setAttributeInternal(APPRAISALHISTLINEID, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for COMPLETE_PERCENT using the alias name CompletePercent.
     * @return the COMPLETE_PERCENT
     */
    public BigDecimal getCompletePercent() {
        return (BigDecimal) getAttributeInternal(COMPLETEPERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPLETE_PERCENT using the alias name CompletePercent.
     * @param value value to set the COMPLETE_PERCENT
     */
    public void setCompletePercent(BigDecimal value) {
        setAttributeInternal(COMPLETEPERCENT, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for DETAIL using the alias name Detail.
     * @return the DETAIL
     */
    public String getDetail() {
        return (String) getAttributeInternal(DETAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for DETAIL using the alias name Detail.
     * @param value value to set the DETAIL
     */
    public void setDetail(String value) {
        setAttributeInternal(DETAIL, value);
    }

    /**
     * Gets the attribute value for MEASURE_COMMENTS using the alias name MeasureComments.
     * @return the MEASURE_COMMENTS
     */
    public String getMeasureComments() {
        return (String) getAttributeInternal(MEASURECOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURE_COMMENTS using the alias name MeasureComments.
     * @param value value to set the MEASURE_COMMENTS
     */
    public void setMeasureComments(String value) {
        setAttributeInternal(MEASURECOMMENTS, value);
    }

    /**
     * Gets the attribute value for MEASURE_NAME using the alias name MeasureName.
     * @return the MEASURE_NAME
     */
    public String getMeasureName() {
        return (String) getAttributeInternal(MEASURENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURE_NAME using the alias name MeasureName.
     * @param value value to set the MEASURE_NAME
     */
    public void setMeasureName(String value) {
        setAttributeInternal(MEASURENAME, value);
    }

    /**
     * Gets the attribute value for MEASURE_TYPE using the alias name MeasureType.
     * @return the MEASURE_TYPE
     */
    public String getMeasureType() {
        return (String) getAttributeInternal(MEASURETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURE_TYPE using the alias name MeasureType.
     * @param value value to set the MEASURE_TYPE
     */
    public void setMeasureType(String value) {
        setAttributeInternal(MEASURETYPE, value);
    }

    /**
     * Gets the attribute value for MEASURE_UOM using the alias name MeasureUom.
     * @return the MEASURE_UOM
     */
    public String getMeasureUom() {
        return (String) getAttributeInternal(MEASUREUOM);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURE_UOM using the alias name MeasureUom.
     * @param value value to set the MEASURE_UOM
     */
    public void setMeasureUom(String value) {
        setAttributeInternal(MEASUREUOM, value);
    }

    /**
     * Gets the attribute value for MEASUREMENT_STYLE using the alias name MeasurementStyle.
     * @return the MEASUREMENT_STYLE
     */
    public String getMeasurementStyle() {
        return (String) getAttributeInternal(MEASUREMENTSTYLE);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASUREMENT_STYLE using the alias name MeasurementStyle.
     * @param value value to set the MEASUREMENT_STYLE
     */
    public void setMeasurementStyle(String value) {
        setAttributeInternal(MEASUREMENTSTYLE, value);
    }

    /**
     * Gets the attribute value for NEXT_REVIEW_DATE using the alias name NextReviewDate.
     * @return the NEXT_REVIEW_DATE
     */
    public Timestamp getNextReviewDate() {
        return (Timestamp) getAttributeInternal(NEXTREVIEWDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for NEXT_REVIEW_DATE using the alias name NextReviewDate.
     * @param value value to set the NEXT_REVIEW_DATE
     */
    public void setNextReviewDate(Timestamp value) {
        setAttributeInternal(NEXTREVIEWDATE, value);
    }

    /**
     * Gets the attribute value for OBJECTIVE_COMMENTS using the alias name ObjectiveComments.
     * @return the OBJECTIVE_COMMENTS
     */
    public String getObjectiveComments() {
        return (String) getAttributeInternal(OBJECTIVECOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECTIVE_COMMENTS using the alias name ObjectiveComments.
     * @param value value to set the OBJECTIVE_COMMENTS
     */
    public void setObjectiveComments(String value) {
        setAttributeInternal(OBJECTIVECOMMENTS, value);
    }

    /**
     * Gets the attribute value for OBJECTIVE_NAME using the alias name ObjectiveName.
     * @return the OBJECTIVE_NAME
     */
    public String getObjectiveName() {
        return (String) getAttributeInternal(OBJECTIVENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECTIVE_NAME using the alias name ObjectiveName.
     * @param value value to set the OBJECTIVE_NAME
     */
    public void setObjectiveName(String value) {
        setAttributeInternal(OBJECTIVENAME, value);
    }

    /**
     * Gets the attribute value for OBJECTIVE_START_DATE using the alias name ObjectiveStartDate.
     * @return the OBJECTIVE_START_DATE
     */
    public Timestamp getObjectiveStartDate() {
        return (Timestamp) getAttributeInternal(OBJECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECTIVE_START_DATE using the alias name ObjectiveStartDate.
     * @param value value to set the OBJECTIVE_START_DATE
     */
    public void setObjectiveStartDate(Timestamp value) {
        setAttributeInternal(OBJECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for OBJECTIVE_TARGET_DATE using the alias name ObjectiveTargetDate.
     * @return the OBJECTIVE_TARGET_DATE
     */
    public Timestamp getObjectiveTargetDate() {
        return (Timestamp) getAttributeInternal(OBJECTIVETARGETDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECTIVE_TARGET_DATE using the alias name ObjectiveTargetDate.
     * @param value value to set the OBJECTIVE_TARGET_DATE
     */
    public void setObjectiveTargetDate(Timestamp value) {
        setAttributeInternal(OBJECTIVETARGETDATE, value);
    }

    /**
     * Gets the attribute value for SUCCESS_CRITERIA using the alias name SuccessCriteria.
     * @return the SUCCESS_CRITERIA
     */
    public String getSuccessCriteria() {
        return (String) getAttributeInternal(SUCCESSCRITERIA);
    }

    /**
     * Sets <code>value</code> as attribute value for SUCCESS_CRITERIA using the alias name SuccessCriteria.
     * @param value value to set the SUCCESS_CRITERIA
     */
    public void setSuccessCriteria(String value) {
        setAttributeInternal(SUCCESSCRITERIA, value);
    }

    /**
     * Gets the attribute value for TARGET_VALUE using the alias name TargetValue.
     * @return the TARGET_VALUE
     */
    public BigDecimal getTargetValue() {
        return (BigDecimal) getAttributeInternal(TARGETVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_VALUE using the alias name TargetValue.
     * @param value value to set the TARGET_VALUE
     */
    public void setTargetValue(BigDecimal value) {
        setAttributeInternal(TARGETVALUE, value);
    }

    /**
     * Gets the attribute value for WEIGHTING_PERCENT using the alias name WeightingPercent.
     * @return the WEIGHTING_PERCENT
     */
    public BigDecimal getWeightingPercent() {
        return (BigDecimal) getAttributeInternal(WEIGHTINGPERCENT);
    }

    /**
     * Sets <code>value</code> as attribute value for WEIGHTING_PERCENT using the alias name WeightingPercent.
     * @param value value to set the WEIGHTING_PERCENT
     */
    public void setWeightingPercent(BigDecimal value) {
        setAttributeInternal(WEIGHTINGPERCENT, value);
    }
}

