package model.vo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 11 19:38:08 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprisalHisLine_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ApprisalHisLine_VOImpl() {
    }

    /**
     * Returns the variable value for b_HistLineId.
     * @return variable value for b_HistLineId
     */
    public BigDecimal getpHistLineId() {
        return (BigDecimal) ensureVariableManager().getVariableValue("pHistLineId");
    }

    /**
     * Sets <code>value</code> for variable b_HistLineId.
     * @param value value to bind as b_HistLineId
     */
    public void setpHistLineId(BigDecimal value) {
        ensureVariableManager().setVariableValue("pHistLineId", value);
    }
}

