package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 09 15:33:28 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprisalHisHdr_VORowImpl extends ViewRowImpl {
    public static final int ENTITY_APPRISALHISHDR_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        AppraisalComments,
        AppraisalDate,
        AppraisalFeedback,
        AppraisalHistHdrId,
        AppraisalPeriodEndDate,
        AppraisalPeriodStartDate,
        AppraisalPurpose,
        BusinessGroupName,
        Initiator,
        OverallRating,
        PersonId,
        SuggestedFinalRating,
        Trans_Name,
        Trans_No,
        Trans_Email,
        Trans_BusinessGroup,
        ApprisalHisLine_VO,
        Employee_View_ROVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int APPRAISALCOMMENTS = AttributesEnum.AppraisalComments.index();
    public static final int APPRAISALDATE = AttributesEnum.AppraisalDate.index();
    public static final int APPRAISALFEEDBACK = AttributesEnum.AppraisalFeedback.index();
    public static final int APPRAISALHISTHDRID = AttributesEnum.AppraisalHistHdrId.index();
    public static final int APPRAISALPERIODENDDATE = AttributesEnum.AppraisalPeriodEndDate.index();
    public static final int APPRAISALPERIODSTARTDATE = AttributesEnum.AppraisalPeriodStartDate.index();
    public static final int APPRAISALPURPOSE = AttributesEnum.AppraisalPurpose.index();
    public static final int BUSINESSGROUPNAME = AttributesEnum.BusinessGroupName.index();
    public static final int INITIATOR = AttributesEnum.Initiator.index();
    public static final int OVERALLRATING = AttributesEnum.OverallRating.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int SUGGESTEDFINALRATING = AttributesEnum.SuggestedFinalRating.index();
    public static final int TRANS_NAME = AttributesEnum.Trans_Name.index();
    public static final int TRANS_NO = AttributesEnum.Trans_No.index();
    public static final int TRANS_EMAIL = AttributesEnum.Trans_Email.index();
    public static final int TRANS_BUSINESSGROUP = AttributesEnum.Trans_BusinessGroup.index();
    public static final int APPRISALHISLINE_VO = AttributesEnum.ApprisalHisLine_VO.index();
    public static final int EMPLOYEE_VIEW_ROVO = AttributesEnum.Employee_View_ROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ApprisalHisHdr_VORowImpl() {
    }

    /**
     * Gets ApprisalHisHdr_EO entity object.
     * @return the ApprisalHisHdr_EO
     */
    public EntityImpl getApprisalHisHdr_EO() {
        return (EntityImpl) getEntity(ENTITY_APPRISALHISHDR_EO);
    }

    /**
     * Gets the attribute value for APPRAISAL_COMMENTS using the alias name AppraisalComments.
     * @return the APPRAISAL_COMMENTS
     */
    public String getAppraisalComments() {
        return (String) getAttributeInternal(APPRAISALCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_COMMENTS using the alias name AppraisalComments.
     * @param value value to set the APPRAISAL_COMMENTS
     */
    public void setAppraisalComments(String value) {
        setAttributeInternal(APPRAISALCOMMENTS, value);
    }

    /**
     * Gets the attribute value for APPRAISAL_DATE using the alias name AppraisalDate.
     * @return the APPRAISAL_DATE
     */
    public Timestamp getAppraisalDate() {
        return (Timestamp) getAttributeInternal(APPRAISALDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_DATE using the alias name AppraisalDate.
     * @param value value to set the APPRAISAL_DATE
     */
    public void setAppraisalDate(Timestamp value) {
        setAttributeInternal(APPRAISALDATE, value);
    }

    /**
     * Gets the attribute value for APPRAISAL_FEEDBACK using the alias name AppraisalFeedback.
     * @return the APPRAISAL_FEEDBACK
     */
    public String getAppraisalFeedback() {
        return (String) getAttributeInternal(APPRAISALFEEDBACK);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_FEEDBACK using the alias name AppraisalFeedback.
     * @param value value to set the APPRAISAL_FEEDBACK
     */
    public void setAppraisalFeedback(String value) {
        setAttributeInternal(APPRAISALFEEDBACK, value);
    }

    /**
     * Gets the attribute value for APPRAISAL_HIST_HDR_ID using the alias name AppraisalHistHdrId.
     * @return the APPRAISAL_HIST_HDR_ID
     */
    public BigDecimal getAppraisalHistHdrId() {
        return (BigDecimal) getAttributeInternal(APPRAISALHISTHDRID);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_HIST_HDR_ID using the alias name AppraisalHistHdrId.
     * @param value value to set the APPRAISAL_HIST_HDR_ID
     */
    public void setAppraisalHistHdrId(BigDecimal value) {
        setAttributeInternal(APPRAISALHISTHDRID, value);
    }

    /**
     * Gets the attribute value for APPRAISAL_PERIOD_END_DATE using the alias name AppraisalPeriodEndDate.
     * @return the APPRAISAL_PERIOD_END_DATE
     */
    public Timestamp getAppraisalPeriodEndDate() {
        return (Timestamp) getAttributeInternal(APPRAISALPERIODENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_PERIOD_END_DATE using the alias name AppraisalPeriodEndDate.
     * @param value value to set the APPRAISAL_PERIOD_END_DATE
     */
    public void setAppraisalPeriodEndDate(Timestamp value) {
        setAttributeInternal(APPRAISALPERIODENDDATE, value);
    }

    /**
     * Gets the attribute value for APPRAISAL_PERIOD_START_DATE using the alias name AppraisalPeriodStartDate.
     * @return the APPRAISAL_PERIOD_START_DATE
     */
    public Timestamp getAppraisalPeriodStartDate() {
        return (Timestamp) getAttributeInternal(APPRAISALPERIODSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_PERIOD_START_DATE using the alias name AppraisalPeriodStartDate.
     * @param value value to set the APPRAISAL_PERIOD_START_DATE
     */
    public void setAppraisalPeriodStartDate(Timestamp value) {
        setAttributeInternal(APPRAISALPERIODSTARTDATE, value);
    }

    /**
     * Gets the attribute value for APPRAISAL_PURPOSE using the alias name AppraisalPurpose.
     * @return the APPRAISAL_PURPOSE
     */
    public String getAppraisalPurpose() {
        return (String) getAttributeInternal(APPRAISALPURPOSE);
    }

    /**
     * Sets <code>value</code> as attribute value for APPRAISAL_PURPOSE using the alias name AppraisalPurpose.
     * @param value value to set the APPRAISAL_PURPOSE
     */
    public void setAppraisalPurpose(String value) {
        setAttributeInternal(APPRAISALPURPOSE, value);
    }

    /**
     * Gets the attribute value for BUSINESS_GROUP_NAME using the alias name BusinessGroupName.
     * @return the BUSINESS_GROUP_NAME
     */
    public String getBusinessGroupName() {
        return (String) getAttributeInternal(BUSINESSGROUPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_GROUP_NAME using the alias name BusinessGroupName.
     * @param value value to set the BUSINESS_GROUP_NAME
     */
    public void setBusinessGroupName(String value) {
        setAttributeInternal(BUSINESSGROUPNAME, value);
    }

    /**
     * Gets the attribute value for INITIATOR using the alias name Initiator.
     * @return the INITIATOR
     */
    public String getInitiator() {
        return (String) getAttributeInternal(INITIATOR);
    }

    /**
     * Sets <code>value</code> as attribute value for INITIATOR using the alias name Initiator.
     * @param value value to set the INITIATOR
     */
    public void setInitiator(String value) {
        setAttributeInternal(INITIATOR, value);
    }

    /**
     * Gets the attribute value for OVERALL_RATING using the alias name OverallRating.
     * @return the OVERALL_RATING
     */
    public String getOverallRating() {
        return (String) getAttributeInternal(OVERALLRATING);
    }

    /**
     * Sets <code>value</code> as attribute value for OVERALL_RATING using the alias name OverallRating.
     * @param value value to set the OVERALL_RATING
     */
    public void setOverallRating(String value) {
        setAttributeInternal(OVERALLRATING, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for SUGGESTED_FINAL_RATING using the alias name SuggestedFinalRating.
     * @return the SUGGESTED_FINAL_RATING
     */
    public BigDecimal getSuggestedFinalRating() {
        return (BigDecimal) getAttributeInternal(SUGGESTEDFINALRATING);
    }

    /**
     * Sets <code>value</code> as attribute value for SUGGESTED_FINAL_RATING using the alias name SuggestedFinalRating.
     * @param value value to set the SUGGESTED_FINAL_RATING
     */
    public void setSuggestedFinalRating(BigDecimal value) {
        setAttributeInternal(SUGGESTEDFINALRATING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Name.
     * @return the Trans_Name
     */
    public String getTrans_Name() {
        BigDecimal id = null;
               String FullName = null;
               if (getPersonId() != null) {
                   id = getPersonId();
                   Row[] deptRows;
                   deptRows = getEmployee_View_ROVO().getFilteredRows("PersonId", id);
                   if (deptRows.length > 0) {
                       FullName = deptRows[0].getAttribute("FullName").toString();
                   }
                   return FullName;
        
               } else {
        return (String) getAttributeInternal(TRANS_NAME);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Name.
     * @param value value to set the  Trans_Name
     */
    public void setTrans_Name(String value) {
       
        setAttributeInternal(TRANS_NAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_No.
     * @return the Trans_No
     */
    public String getTrans_No() {
        BigDecimal id = null;
               String FullName = null;
               if (getPersonId() != null) {
                   id = getPersonId();
                   Row[] deptRows;
                   deptRows = getEmployee_View_ROVO().getFilteredRows("PersonId", id);
                   if (deptRows.length > 0) {
                       FullName = deptRows[0].getAttribute("PersonNumber").toString();
                   }
                   return FullName;
        
               } else {
        return (String) getAttributeInternal(TRANS_NO);
    }}

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_No.
     * @param value value to set the  Trans_No
     */
    public void setTrans_No(String value) {
        setAttributeInternal(TRANS_NO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Email.
     * @return the Trans_Email
     */
    public String getTrans_Email() {
        BigDecimal id = null;
               String FullName = null;
               if (getPersonId() != null) {
                   id = getPersonId();
                   Row[] deptRows;
                   deptRows = getEmployee_View_ROVO().getFilteredRows("PersonId", id);
                   if (deptRows.length > 0) {
                       FullName = deptRows[0].getAttribute("EmailAddress").toString();
                   }
                   return FullName;
        
               } else {
        return (String) getAttributeInternal(TRANS_EMAIL);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Email.
     * @param value value to set the  Trans_Email
     */
    public void setTrans_Email(String value) {
        setAttributeInternal(TRANS_EMAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_BusinessGroup.
     * @return the Trans_BusinessGroup
     */
    public String getTrans_BusinessGroup() {
        BigDecimal id = null;
               String FullName = null;
               if (getPersonId() != null) {
                   id = getPersonId();
                   Row[] deptRows;
                   deptRows = getEmployee_View_ROVO().getFilteredRows("PersonId", id);
                   if (deptRows.length > 0) {
                       FullName = deptRows[0].getAttribute("BusinessUnitName").toString();
                   }
                   return FullName;
        
               } else {
        return (String) getAttributeInternal(TRANS_BUSINESSGROUP);}
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_BusinessGroup.
     * @param value value to set the  Trans_BusinessGroup
     */
    public void setTrans_BusinessGroup(String value) {
        setAttributeInternal(TRANS_BUSINESSGROUP, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ApprisalHisLine_VO.
     */
    public RowIterator getApprisalHisLine_VO() {
        return (RowIterator) getAttributeInternal(APPRISALHISLINE_VO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Employee_View_ROVO.
     */
    public RowSet getEmployee_View_ROVO() {
        return (RowSet) getAttributeInternal(EMPLOYEE_VIEW_ROVO);
    }
}

