package model.vo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 09 15:33:30 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprisalHisHdr_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ApprisalHisHdr_VOImpl() {
    }

    /**
     * Returns the variable value for BV_ID.
     * @return variable value for BV_ID
     */
    public BigDecimal getBV_ID() {
        return (BigDecimal) ensureVariableManager().getVariableValue("BV_ID");
    }

    /**
     * Sets <code>value</code> for variable BV_ID.
     * @param value value to bind as BV_ID
     */
    public void setBV_ID(BigDecimal value) {
        ensureVariableManager().setVariableValue("BV_ID", value);
    }

    /**
     * Returns the bind variable value for b_username.
     * @return bind variable value for b_username
     */
    public String getb_username() {
        return (String) getNamedWhereClauseParam("b_username");
    }

    /**
     * Sets <code>value</code> for bind variable b_username.
     * @param value value to bind as b_username
     */
    public void setb_username(String value) {
        setNamedWhereClauseParam("b_username", value);
    }
}

